language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
